# Generated by Django 4.2 on 2023-04-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0004_rename_name_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
