# Generated by Django 4.2 on 2023-04-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0005_rename_first_name_user_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
