# Generated by Django 4.2 on 2023-04-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0006_user_last_login_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
