# Generated by Django 4.2 on 2023-04-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0009_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=50),
        ),
    ]
