# Generated by Django 4.2 on 2023-04-26 23:16

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0010_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed',
            field=embed_video.fields.EmbedVideoField(default=0),
            preserve_default=False,
        ),
    ]
