# Generated by Django 4.2 on 2023-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0011_video_embed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_language', models.CharField(max_length=100)),
                ('how_did_you_find_us', models.CharField(max_length=100)),
                ('level_of_interest', models.IntegerField()),
                ('reason_for_learning', models.TextField()),
                ('time_to_dedicate', models.CharField(max_length=100)),
            ],
        ),
    ]
