# Generated by Django 4.2 on 2023-05-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0013_quiz_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainYmay.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainYmay.user')),
            ],
        ),
    ]
