# Generated by Django 4.2 on 2023-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0014_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='video',
        ),
        migrations.AddField(
            model_name='quiz',
            name='videos',
            field=models.ManyToManyField(to='mainYmay.video'),
        ),
    ]
