# Generated by Django 4.2 on 2023-06-01 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0015_remove_quiz_video_quiz_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mainYmay.video'),
            preserve_default=False,
        ),
    ]
