# Generated by Django 4.2 on 2023-06-01 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0018_video_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainYmay.answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainYmay.quiz'),
            preserve_default=False,
        ),
    ]
