# Generated by Django 4.2 on 2023-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0019_userprogress_answer_userprogress_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'quiz', 'question')},
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='date_completed',
        ),
    ]
