# Generated by Django 4.2 on 2023-06-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainYmay', '0020_userprogress_is_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainYmay.user')),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
